name = "SoleViz"
uuid = "fc840457-d78a-47de-ac4f-ba01d7af495c"
authors = ["Eduard I. STAN", "Giovanni PAGLIARINI", "Federico MANZELLA"]
version = "0.1.0"

[deps]
SoleBase = "142d03a6-36c4-4bac-9273-c7ed2abbbb4d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
